=== CovOpen/CovQuestions/react-with-json-logic/public/api/schema/questionnaire.json
{
  "$ref": "#/definitions/IQuestionnaire",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "INumericOption": {
      "additionalProperties": false,
      "description": "Option for numeric questions.",
      "properties": {
        "defaultValue": {
          "description": "Default value",
          "type": "number"
        },
        "max": {
          "description": "maximal value",
          "type": "number"
        },
        "min": {
          "description": "Minimal value",
          "type": "number"
        },
        "step": {
          "description": "Step size",
          "type": "number"
        }
      },
      "type": "object"
    },
    "INumericQuestion": {
      "additionalProperties": false,
      "properties": {
        "details": {
          "description": "Optional human-readable details or clarifiation about this question.",
          "type": "string"
        },
        "enableWhen": {
          "$ref": "#/definitions/LogicExpression",
          "description": "Logic expression to decide whether the question should be displayed or not.\nDefaults to true."
        },
        "id": {
          "description": "Unique id for referring this question in logic expressions.",
          "type": "string"
        },
        "numericOptions": {
          "$ref": "#/definitions/INumericOption",
          "description": "Answer options for Select/Multiselect questions."
        },
        "optional": {
          "description": "Boolean indicating whether the question is optional or not.",
          "type": "boolean"
        },
        "text": {
          "description": "Human-readable question text, can be localized.",
          "type": "string"
        },
        "type": {
          "description": "Type of the question.",
          "enum": ["number"],
          "type": "string"
        }
      },
      "required": ["id", "text", "type"],
      "type": "object"
    },
    "IOption": {
      "additionalProperties": false,
      "description": "Option for multi-select questions.",
      "properties": {
        "asQuestion": {
          "description": "Human-Readable formulation of this option as yes/no question.\nThis is for use-cases where multi-selects are not possible in the UI,\nfor example telephone hotlines.",
          "type": "string"
        },
        "text": {
          "description": "Human-Readable answer, can be localized.",
          "type": "string"
        },
        "value": {
          "description": "Value used for evaluating logic expressions.",
          "type": "string"
        }
      },
      "required": ["text", "value"],
      "type": "object"
    },
    "IQuestion": {
      "anyOf": [
        {
          "$ref": "#/definitions/IQuestionWithoutOptions"
        },
        {
          "$ref": "#/definitions/IQuestionWithOptions"
        },
        {
          "$ref": "#/definitions/INumericQuestion"
        }
      ]
    },
    "IQuestionWithOptions": {
      "additionalProperties": false,
      "properties": {
        "details": {
          "description": "Optional human-readable details or clarifiation about this question.",
          "type": "string"
        },
        "enableWhen": {
          "$ref": "#/definitions/LogicExpression",
          "description": "Logic expression to decide whether the question should be displayed or not.\nDefaults to true."
        },
        "id": {
          "description": "Unique id for referring this question in logic expressions.",
          "type": "string"
        },
        "optional": {
          "description": "Boolean indicating whether the question is optional or not.",
          "type": "boolean"
        },
        "options": {
          "description": "Answer options for Select/Multiselect questions.",
          "items": {
            "$ref": "#/definitions/IOption"
          },
          "type": "array"
        },
        "text": {
          "description": "Human-readable question text, can be localized.",
          "type": "string"
        },
        "type": {
          "anyOf": [
            {
              "enum": ["select"],
              "type": "string"
            },
            {
              "enum": ["multiselect"],
              "type": "string"
            }
          ],
          "description": "Type of the question."
        }
      },
      "required": ["id", "text", "type"],
      "type": "object"
    },
    "IQuestionWithoutOptions": {
      "additionalProperties": false,
      "properties": {
        "details": {
          "description": "Optional human-readable details or clarifiation about this question.",
          "type": "string"
        },
        "enableWhen": {
          "$ref": "#/definitions/LogicExpression",
          "description": "Logic expression to decide whether the question should be displayed or not.\nDefaults to true."
        },
        "id": {
          "description": "Unique id for referring this question in logic expressions.",
          "type": "string"
        },
        "optional": {
          "description": "Boolean indicating whether the question is optional or not.",
          "type": "boolean"
        },
        "text": {
          "description": "Human-readable question text, can be localized.",
          "type": "string"
        },
        "type": {
          "anyOf": [
            {
              "enum": ["boolean"],
              "type": "string"
            },
            {
              "enum": ["date"],
              "type": "string"
            },
            {
              "enum": ["text"],
              "type": "string"
            }
          ],
          "description": "Type of the question."
        }
      },
      "required": ["id", "text", "type"],
      "type": "object"
    },
    "IQuestionnaire": {
      "additionalProperties": false,
      "description": "The questionaire.",
      "properties": {
        "id": {
          "description": "Unique, assigned identifier. Machine friendly.",
          "type": "string"
        },
        "meta": {
          "$ref": "#/definitions/IQuestionnaireMeta",
          "description": "Meta-Information."
        },
        "questions": {
          "description": "All questions, shown one after another, in order.",
          "items": {
            "$ref": "#/definitions/IQuestion"
          },
          "type": "array"
        },
        "resultCategories": {
          "description": "All result categories. When all questions are answered,\nthe result for each result category is computed.",
          "items": {
            "$ref": "#/definitions/IResultCategory"
          },
          "type": "array"
        },
        "schemaVersion": {
          "description": "File format/api version in semver.",
          "type": "string"
        },
        "variables": {
          "description": "All variables, refreshed after each update to any answer.",
          "items": {
            "$ref": "#/definitions/IVariable"
          },
          "type": "array"
        },
        "version": {
          "description": "Version of this question in semver.",
          "type": "string"
        }
      },
      "required": ["id", "schemaVersion", "version", "meta", "questions", "variables", "resultCategories"],
      "type": "object"
    },
    "IQuestionnaireMeta": {
      "additionalProperties": false,
      "description": "Meta-Information for a questionaire.",
      "properties": {
        "author": {
          "type": "string"
        },
        "creationDate": {
          "description": "Creation date as ISO 8601 string",
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "experiationDate": {
          "description": "Expiration date as ISO 8601 string",
          "type": "string"
        },
        "language": {
          "description": "Language of this questionaire, as ISO 639-1 code.\nNote that further languages can be defined in external lookup files.",
          "type": "string"
        },
        "publisher": {
          "type": "string"
        },
        "regions": {
          "description": "Region restriction (e.g. regions in which this questionaire is valid) as list of ISO 3166 ids.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "title": {
          "type": "string"
        }
      },
      "required": ["title", "author", "language", "creationDate"],
      "type": "object"
    },
    "IResult": {
      "additionalProperties": false,
      "description": "Represents a single result.",
      "properties": {
        "id": {
          "description": "A unique identifier for this result.",
          "type": "string"
        },
        "text": {
          "description": "A human readable text for this result. Can be localized.",
          "type": "string"
        },
        "value": {
          "$ref": "#/definitions/LogicExpression",
          "description": "A logic expression yielding true or false. The first result in the result category yielding true will be\nused as result. If no result evaluates to true, no result is shown for this category."
        }
      },
      "required": ["id", "text", "value"],
      "type": "object"
    },
    "IResultCategory": {
      "additionalProperties": false,
      "description": "Represents a result category. A category might yield exactly one or zero results at the end of the questionaire.",
      "properties": {
        "description": {
          "description": "A human readable description for the result category. Can be localized.",
          "type": "string"
        },
        "id": {
          "description": "A unique identifier for this result category.",
          "type": "string"
        },
        "results": {
          "description": "A list of results for this category.",
          "items": {
            "$ref": "#/definitions/IResult"
          },
          "type": "array"
        }
      },
      "required": ["id", "description", "results"],
      "type": "object"
    },
    "IVariable": {
      "additionalProperties": false,
      "description": "Represents a variable which is computed from the given answers or other variables.",
      "properties": {
        "id": {
          "description": "Unique id for referring this variable in logic expressions.",
          "type": "string"
        },
        "value": {
          "$ref": "#/definitions/LogicExpression",
          "description": "Logic expression used to compute this variable."
        }
      },
      "required": ["id", "value"],
      "type": "object"
    },
    "LogicAnd": {
      "additionalProperties": false,
      "properties": {
        "and": {
          "items": {
            "$ref": "#/definitions/LogicExpression"
          },
          "type": "array"
        }
      },
      "required": ["and"],
      "type": "object"
    },
    "LogicConstant": {
      "type": ["number", "string", "boolean"]
    },
    "LogicEquals": {
      "additionalProperties": false,
      "properties": {
        "==": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": ["=="],
      "type": "object"
    },
    "LogicExpression": {
      "anyOf": [
        {
          "$ref": "#/definitions/LogicOperator"
        },
        {
          "$ref": "#/definitions/LogicVariable"
        },
        {
          "$ref": "#/definitions/LogicConstant"
        }
      ]
    },
    "LogicGreater": {
      "additionalProperties": false,
      "properties": {
        ">": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": [">"],
      "type": "object"
    },
    "LogicGreaterEqual": {
      "additionalProperties": false,
      "properties": {
        ">=": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": [">="],
      "type": "object"
    },
    "LogicIf": {
      "additionalProperties": false,
      "properties": {
        "if": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 3,
          "minItems": 3,
          "type": "array"
        }
      },
      "required": ["if"],
      "type": "object"
    },
    "LogicIn": {
      "additionalProperties": false,
      "properties": {
        "in": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "items": {
                "$ref": "#/definitions/LogicExpression"
              },
              "type": "array"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": ["in"],
      "type": "object"
    },
    "LogicLess": {
      "additionalProperties": false,
      "properties": {
        "<": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": ["<"],
      "type": "object"
    },
    "LogicLessEqual": {
      "additionalProperties": false,
      "properties": {
        "<=": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": ["<="],
      "type": "object"
    },
    "LogicMinus": {
      "additionalProperties": false,
      "properties": {
        "-": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": ["-"],
      "type": "object"
    },
    "LogicNot": {
      "additionalProperties": false,
      "properties": {
        "!": {
          "anyOf": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "items": {
                "$ref": "#/definitions/LogicExpression"
              },
              "type": "array"
            }
          ]
        }
      },
      "required": ["!"],
      "type": "object"
    },
    "LogicOperator": {
      "anyOf": [
        {
          "$ref": "#/definitions/LogicIf"
        },
        {
          "$ref": "#/definitions/LogicReduce"
        },
        {
          "$ref": "#/definitions/LogicSome"
        },
        {
          "$ref": "#/definitions/LogicEquals"
        },
        {
          "$ref": "#/definitions/LogicGreaterEqual"
        },
        {
          "$ref": "#/definitions/LogicNot"
        },
        {
          "$ref": "#/definitions/LogicLessEqual"
        },
        {
          "$ref": "#/definitions/LogicPlus"
        },
        {
          "$ref": "#/definitions/LogicMinus"
        },
        {
          "$ref": "#/definitions/LogicAnd"
        },
        {
          "$ref": "#/definitions/LogicOr"
        },
        {
          "$ref": "#/definitions/LogicIn"
        },
        {
          "$ref": "#/definitions/LogicGreater"
        },
        {
          "$ref": "#/definitions/LogicLess"
        }
      ]
    },
    "LogicOr": {
      "additionalProperties": false,
      "properties": {
        "or": {
          "items": {
            "$ref": "#/definitions/LogicExpression"
          },
          "type": "array"
        }
      },
      "required": ["or"],
      "type": "object"
    },
    "LogicPlus": {
      "additionalProperties": false,
      "properties": {
        "+": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": ["+"],
      "type": "object"
    },
    "LogicReduce": {
      "additionalProperties": false,
      "properties": {
        "reduce": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 3,
          "minItems": 3,
          "type": "array"
        }
      },
      "required": ["reduce"],
      "type": "object"
    },
    "LogicSome": {
      "additionalProperties": false,
      "properties": {
        "some": {
          "items": [
            {
              "$ref": "#/definitions/LogicExpression"
            },
            {
              "$ref": "#/definitions/LogicExpression"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": ["some"],
      "type": "object"
    },
    "LogicVariable": {
      "additionalProperties": false,
      "properties": {
        "var": {
          "type": "string"
        }
      },
      "required": ["var"],
      "type": "object"
    }
  }
}

=== CovOpen/CovQuestions/api/v1/src/questionnaires/simpleTextQuestion/questionnaire.json
{
  "id": "simpleTextQuestion",
  "schemaVersion": "1",
  "version": "1",
  "meta": {
    "author": "Someone",
    "language": "DE",
    "title": "Simple text question",
    "creationDate": "2020-04-13T14:48:48+0000"
  },
  "questions": [
    {
      "id": "q1_text",
      "text": "Geben Sie bitte 'test' ein um ein Resultat zu sehen.",
      "type": "text",
      "optional": true
    }
  ],
  "variables": [],
  "resultCategories": [
    {
      "id": "rc_text",
      "description": "Text",
      "results": [
        {
          "id": "TEXT",
          "text": "Sie k√∂nnen simple Anweisungen befolgen.",
          "value": {
            "==": [
              {
                "var": "q1_text.value"
              },
              "test"
            ]
          }
        }
      ]
    }
  ]
}

=== CovOpen/CovQuestions/api/v1/test/apiCompareFile/questionnaires/testQuestionnaire1/1/de.json
{
  "id": "testQuestionnaire1",
  "schemaVersion": "1",
  "version": "1",
  "meta": {
    "author": "Someone",
    "language": "de",
    "title": "test Befragung",
    "creationDate": "2020-04-13T14:48:48+0000"
  },
  "questions": [
    {
      "id": "q1_text",
      "text": "Bitte gib 'test' ein um das Ergebnis zu sehen.",
      "type": "text",
      "optional": true
    }
  ],
  "variables": [],
  "resultCategories": [
    {
      "id": "rc_text",
      "description": "Text",
      "results": [
        {
          "id": "TEXT",
          "text": "Wuhu! Du hast den Anweisung folge geleistet.",
          "value": {
            "==": [
              {
                "var": "q1_text.value"
              },
              "test"
            ]
          }
        }
      ]
    }
  ]
}

=== CovOpen/CovQuestions/api/v1/src/data/questionnaires/simpleBooleanContactQuestion.json
{
  "id": "simpleBooleanContactQuestion",
  "schemaVersion": "1",
  "version": "1",
  "meta": {
    "author": "Someone",
    "language": "DE",
    "title": "Simple boolean contact question",
    "creationDate": "2020-04-10T18:48:48+0000"
  },
  "questions": [
    {
      "id": "q1_contact",
      "text": "Gab es Kontakt zu bestätigten Fällen?",
      "type": "boolean"
    }
  ],
  "variables": [],
  "resultCategories": [
    {
      "id": "rc_contact",
      "description": "Kontakt",
      "results": [
        {
          "id": "CONTACT_YES",
          "text": "Sie hatten Kontakt.",
          "value": {
            "var": "q1_contact.value"
          }
        },
        {
          "id": "CONTACT_NO",
          "text": "Sie hatten keinen Kontakt.",
          "value": {
            "!": {
              "var": "q1_contact.value"
            }
          }
        }
      ]
    }
  ]
}

=== CovOpen/CovQuestions/react-with-json-logic/public/api/simpleMultiselectSymptomsQuestion.json
{
  "id": "simpleMultiselectSymptomsQuestion",
  "schemaVersion": "1",
  "version": "1",
  "meta": {
    "author": "Someone",
    "language": "DE",
    "title": "Simple multiselect symptoms question",
    "creationDate": "2020-04-13T13:48:48+0000"
  },
  "questions": [
    {
      "id": "q1_symptoms",
      "text": "Welche der folgenden Symptome haben Sie?",
      "type": "multiselect",
      "options": [
        {
          "text": "Husten",
          "value": "cough"
        },
        {
          "text": "Schnupfen",
          "value": "headCold"
        },
        {
          "text": "Fieber",
          "value": "fever"
        },
        {
          "text": "Atemnot",
          "value": "breathlessness"
        }
      ]
    }
  ],
  "variables": [],
  "resultCategories": [
    {
      "id": "rc_symptoms",
      "description": "Symptome",
      "results": [
        {
          "id": "MANY_SYMPTOMS",
          "text": "Sie haben drei oder mehr Symptome.",
          "value": {
            ">=": [
              {
                "var": "q1_symptoms.selectedCount"
              },
              3
            ]
          }
        },
        {
          "id": "FEW_SYMPTOMS",
          "text": "Sie haben ein oder zwei Symptome.",
          "value": {
            "or": [
              {
                "==": [
                  {
                    "var": "q1_symptoms.selectedCount"
                  },
                  1
                ]
              },
              {
                "==": [
                  {
                    "var": "q1_symptoms.selectedCount"
                  },
                  2
                ]
              }
            ]
          }
        },
        {
          "id": "NO_SYMPTOMS",
          "text": "Sie haben keine Symptome.",
          "value": {
            "==": [
              {
                "var": "q1_symptoms.selectedCount"
              },
              0
            ]
          }
        }
      ]
    }
  ]
}

=== CovOpen/CovQuestions/api/v1/questionnaires/simpleTextQuestion/v1/questionnaire-en.json
{"id": "simpleTextQuestion", "schemaVersion": "1", "version": "1", "meta": {"author": "Someone", "language": "en", "title": "Simple text question", "creationDate": "2020-04-13T14:48:48+0000"}, "questions": [{"id": "q1_text", "text": "Please insert 'test' to see a result.", "type": "text", "optional": true}], "variables": [], "resultCategories": [{"id": "rc_text", "description": "Text", "results": [{"id": "TEXT", "text": "You are able to follow simple instructions", "value": {"==": [{"var": "q1_text.value"}, "test"]}}]}]}
